# Generated by Django 4.2.18 on 2025-01-23 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="taskdetail",
            name="priority",
            field=models.CharField(
                choices=[("H", "High"), ("M", "Medium"), ("L", "Low")],
                default="L",
                max_length=6,
            ),
        ),
    ]
