# Generated by Django 4.2.18 on 2025-01-23 19:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0002_alter_taskdetail_priority"),
    ]

    operations = [
        migrations.RemoveField(model_name="taskdetail", name="assigned_to",),
    ]
