# Generated by Django 4.2.18 on 2025-01-21 09:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0005_employee_task_assigned_to"),
    ]

    operations = [
        migrations.AlterField(
            model_name="taskdetail",
            name="task",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="details",
                to="tasks.task",
            ),
        ),
    ]
